In [1]:
import torch
from torch import linalg as LA
ones = torch.ones((64,3))

In [2]:
torch.norm(ones, 2, keepdim=True)

tensor(13.8564)

In [1]:
from data.loc_data import LocData
r = 0.8
max_deg = 30
max_x = 30
min_x = r
data_len = 100

loc_data = LocData(r, max_deg, max_x, data_len)

loc_data_sample = loc_data._sample_data()


/home/lichen/.conda/envs/py310/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


> /home/lichen/code/UW/auv_location_pl-master/data/geometry.py(72)cord2rad()
     70         pdb.set_trace()
     71         # 弧度，如果要算角度，使用np.degrees()
---> 72         alpha = DB.angle_between(DC)
     73         beta =  DA.angle_between(DC)
     74         gamma = DA.angle_between(DB)



In [17]:
import torch
a = torch.tensor([1,2,3], dtype=torch.float).unsqueeze(0).repeat((4, 1))
b = torch.tensor([4,5,6], dtype=torch.float).unsqueeze(0).repeat((4, 1))
# c = torch.dot(a, b)

In [9]:
(0.0231-0.0181)/(0.9273-0.0181)

0.005499340079190495

In [24]:
d= torch.mul(a, b)
e = torch.norm(a, 2, dim=1)

In [28]:
f = torch.einsum('ij, ij -> i', [a, b])

In [30]:
f.shape

torch.Size([4])

In [33]:
f/e

tensor([8.5524, 8.5524, 8.5524, 8.5524])

In [35]:
import numpy as np

180/np.pi

57.29577951308232

In [37]:
0.1 *180/np.pi

5.729577951308232

In [38]:
30 * 3.14 /180

0.5233333333333333

In [5]:
from ptflops import get_model_complexity_info
from models.layers import MLP 
input_size = 3
hidden_units = [6, 12, 24, 12, 6, 3]
mlp = MLP(input_size, hidden_units)

flops, params = get_model_complexity_info(mlp, (1, 3), as_strings=True, print_per_layer_stat=True)

MLP(
  831, 100.000% Params, 894.0 Mac, 100.000% MACs, 
  (model): Sequential(
    831, 100.000% Params, 894.0 Mac, 100.000% MACs, 
    (0): Flatten(0, 0.000% Params, 0.0 Mac, 0.000% MACs, start_dim=1, end_dim=-1)
    (1): Linear(24, 2.888% Params, 24.0 Mac, 2.685% MACs, in_features=3, out_features=6, bias=True)
    (2): ReLU(0, 0.000% Params, 6.0 Mac, 0.671% MACs, )
    (3): Linear(84, 10.108% Params, 84.0 Mac, 9.396% MACs, in_features=6, out_features=12, bias=True)
    (4): ReLU(0, 0.000% Params, 12.0 Mac, 1.342% MACs, )
    (5): Linear(312, 37.545% Params, 312.0 Mac, 34.899% MACs, in_features=12, out_features=24, bias=True)
    (6): ReLU(0, 0.000% Params, 24.0 Mac, 2.685% MACs, )
    (7): Linear(300, 36.101% Params, 300.0 Mac, 33.557% MACs, in_features=24, out_features=12, bias=True)
    (8): ReLU(0, 0.000% Params, 12.0 Mac, 1.342% MACs, )
    (9): Linear(78, 9.386% Params, 78.0 Mac, 8.725% MACs, in_features=12, out_features=6, bias=True)
    (10): ReLU(0, 0.000% Params, 6.0 Mac, 0.

In [6]:
flops

'894.0 Mac'

In [7]:
params

'831'

In [15]:
import numpy as np
d = 1
r = 0.8

OA = np.sqrt(3)*r/3.
DA = np.sqrt(d**2 + OA**2)

# 夹角计算
alpha = np.arccos((DA**2 + DA**2 - r**2)/(2*DA*DA))
print(alpha)

0.7432640250097023


In [17]:
import sympy as sp
x= sp.symbols('x')
# 距离计算
def f(x):
    a = r**2 / 4
    b = r**2 / 3
    y = sp.sqrt(a/(sp.sin(x/2)**2)-b)
    # y = sp.sqrt(r**2/4./(sp.sin(x/2)**2) - ((r, 3)/3)**2)
    return y
# 求导
fprime = sp.diff(f(x),x)

deltaF = fprime.evalf(subs={x:alpha})

deltaF*0.5

-0.778292884982778

In [1]:
import numpy as np
np.radians(60)

1.0471975511965976

In [2]:
60 / 180 * np.pi

1.0471975511965976

In [4]:
np.sqrt(3) /6

0.28867513459481287

In [5]:
0.0188 * 190/np.pi

1.1370029134485002

In [6]:
import torch
from models.mas import MultiHeadAttention
from models.max import VasNet

# 创建一个多头注意力层，输入维度为3，输出维度为3，头数为1
mha = MultiHeadAttention(input_dim=3,output_dim=3,num_heads=3)
# 创建一个随机输入，批量大小为4，序列长度为5，输入维度为3
x = torch.randn(4 ,6 ,3)
# 前向传播，得到输出
y = mha(x)
# 输出形状为[4 ,5 ,3]，即[批量大小，序列长度，输出维度]
print(y.shape)


vas = VasNet(3, 3, 4, 12)


torch.Size([4, 6, 3])


In [22]:
import torch
from models.layers import Attention_seq

att = Attention_seq(query_dim = 3, heads = 100, dim_head = 10)
x = torch.randn(4 ,6 ,3)
# 前向传播，得到输出
y = att(x)
print(y[0].shape)

torch.Size([4, 6, 3])


In [3]:
from models.mas import AttEncoder
import torch

dim_list = []
# dim_in_feats = 1
# dim_ff = 6
# dim_out_feats = 1
# heads = 3
# dim_head = 12
dim_list.append({'dim_in': 1, 
                 'dim_ff': 6,
                 'dim_out': 6,
                 'head': 3,
                 'dim_head': 12,
                 }
                 )
dim_list.append({'dim_in': 6, 
                 'dim_ff': 12,
                 'dim_out': 12,
                 'head': 3,
                 'dim_head': 12,
                 }
                 )
# dim_list.append({'dim_in': 12, 
#                  'dim_ff': 6,
#                  'dim_out': 24,
#                  'head': 3,
#                  'dim_head': 12,
#                  }
#                  )

net = AttEncoder(dim_list)
x = torch.randn(4, 3, 1)
# net


In [4]:
y = net(x)

RuntimeError: The size of tensor a (6) must match the size of tensor b (12) at non-singleton dimension 2

In [20]:
y.shape

torch.Size([4, 3, 1])

In [17]:
y

tensor([[[ 1.4201e-05],
         [-1.2198e-08],
         [ 2.9017e-06]],

        [[-7.5287e-07],
         [-1.3637e-06],
         [ 5.4372e-07]],

        [[-7.0595e-06],
         [-4.3592e-06],
         [ 4.8147e-06]],

        [[-3.6498e-06],
         [ 1.2080e-06],
         [-8.6904e-07]]], grad_fn=<NativeLayerNormBackward0>)

In [2]:
for i in range(2,10,1):
    print(i)

2
3
4
5
6
7
8
9


In [4]:
import torch.nn as nn 
import torch

pe = nn.Parameter(torch.eye(3), requires_grad=False)
# x = nn.Parameter(torch.tensor(1, 0, 0), requires_grad=False)
# y = nn.Parameter(torch.tensor(0, 1, 0), requires_grad=False)
# z = nn.Parameter(torch.tensor(0, 0, 1), requires_grad=False)
x =  torch.randn(8,3,1)
# pe = torch.stack((x, y, z), dim = 1)
y =  torch.cat([x, pe.expand((8,3,3))], dim = -1)


In [9]:

b, l, d = x.shape

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

if __name__ == "__main__":
    x_list = []
    y_list = []
    z_list = []
    r_list = []

    N = 1000000

    f = open("../shared/dataset.txt", "w")
    rr = np.random.uniform(0, 30000, N)
    fai = np.random.uniform(0, np.pi, N)
    theta = np.random.uniform(0, np.pi * 2, N)
    cnt = 0

    xx = rr * np.sin(theta) * np.cos(fai)
    yy = rr * np.sin(theta) * np.cos(fai)
    zz = rr * np.cos(theta)

    for i in range(N):
        x = xx[i]
        y = yy[i]
        z = zz[i]
        r = np.sqrt(x * x + y * y + z * z)

        if z > 0:
            continue
        if r > 30000:
            continue
        cnt += 1

        p1 = np.array([[400], [0], [0]])
        p2 = np.array([[-400], [0], [0]])
        p3 = np.array([[0], [400 * np.sqrt(3)], [0]])

        T = np.array([[x], [y], [z]])

        op1 = p1 + T
        op2 = p2 + T
        op3 = p3 + T

        e1 = op1 / np.linalg.norm(op1)
        e2 = op2 / np.linalg.norm(op2)
        e3 = op3 / np.linalg.norm(op3)

        print("[{}] [INPUT]e1=({:.6f},{:.6f},{:.6f}) e2=({:.6f},{:.6f},{:.6f}) e3=({:.6f},{:.6f},{:.6f}) "
              "[OUTPUT](tx,ty,tz)=({:.6f},{:.6f},{:.6f})".format(i, e1[0][0], e1[1][0], e1[2][0], e2[0][0], e2[1][0], e2[2][0], e3[0][0], e3[1][0], e3[2][0], x, y, z))

        f.write("{}\n".format(cnt))
        f.write("{:.6f} {:.6f} {:.6f}\n".format(e1[0][0], e1[1][0], e1[2][0]))
        f.write("{:.6f} {:.6f} {:.6f}\n".format(e2[0][0], e2[1][0], e2[2][0]))
        f.write("{:.6f} {:.6f} {:.6f}\n".format(e3[0][0], e3[1][0], e3[2][0]))
        f.write("{:.6f} {:.6f} {:.6f}\n".format(x, y, z))

        x_list.append(x)
        y_list.append(y)
        z_list.append(z)
        r_list.append(r)

    f.write("-1\n")
    f.close()

    # plt.suptitle("Distribution")
    # plt.subplot(2, 2, 1)
    # plt.title("x")
    # plt.hist(np.array(x_list), 1000)
    # plt.subplot(2, 2, 2)
    # plt.title("y")
    # plt.hist(np.array(y_list), 1000)
    # plt.subplot(2, 2, 3)
    # plt.title("z")
    # plt.hist(np.array(z_list), 1000)
    # plt.subplot(2, 2, 4)
    # plt.title("r")
    # plt.hist(np.array(r_list), 1000)
    # plt.show()


In [2]:
rr

array([26695.65807722,  9356.07993572, 23698.96333304, 16039.19777351,
        1863.74496058, 17120.84681396, 10062.88615396, 16007.77064822,
       23790.35683125, 10053.70416612])

In [3]:
import torch
from data.geometry import Vector3D

T = Vector3D([1, 1, 1])
t = T.vertical_angle

t


Vector3D(35.2644)

In [2]:
t

Vector3D(45.)

In [1]:
from data.loc_data import LocData
import numpy as np
r = 0.8
max_deg = 30
max_x = 25
max_rad = np.radians(max_deg, dtype=np.float32)
max_d = np.sqrt(max_x * max_x + 2 * (max_x * np.tan(max_rad)) ** 2)

data_len = 100

ldata = LocData(r, max_deg, max_d, max_x, None, data_len)

/home/lichen/.conda/envs/py310/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
a1, b1, c1, T, t, d, d_max = ldata._sample_data()

In [5]:
a1

Vector3D([ 0.9195, -0.3925, -0.0190])

In [6]:
A1

NameError: name 'A1' is not defined

In [7]:
a1 * d

Vector3D([125345.0312, -53508.6641,  -2590.0686])

In [8]:
T

Vector3D([125192.3828, -53443.5039,  -7205.7168])

In [9]:
t

Vector3D([ 0.9184, -0.3921, -0.0529])

In [10]:
t*d

Vector3D([125192.3828, -53443.5039,  -7205.7168])

In [11]:
d

Vector3D(136313.1094)

In [12]:
A1-T

NameError: name 'A1' is not defined

In [11]:
B1-T

Vector3D([    0.0000, -4000.0000, -2309.4014])

In [12]:
C1-T

Vector3D([    0.0000,  4000.0000, -2309.4014])

In [14]:
ldata.A

Vector3D([   0.0000,    0.0000, 4618.8022])